### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by walwalwalides** [jmarioguedes/exemplo_sismic_image#1]
" **AsType** " : the compiler doesn't recognize

oInner := oJSON.GetValue('Imagem').AsType<TJSONObject>;
Result := oInner.GetValue('imagem').AsType<string>;

thx,good continuation

**Comment by jmarioguedes** [comment]
Hello! What version of your Delphi?

I'm using Delphi River and everything works fine.

Thanks for message.

**Comment by walwalwalides** [comment]
Hello , I am using Delphi Berlin version (compiler version 31),we have different compiler version ,Its most likely the cause of echo :).

**Comment by jmarioguedes** [comment]
That's weird! This feature already exists in Berlin ...

Just to make sure. The lines are these?

```
oInner: = oJSON.GetValue ('Image'). AsType <TJSONObject>;
  Result: = oInner.GetValue ('image') AsType <string>;
```

Your message was missing the `AsType` types.
